repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.7
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier-plugin-tailwindcss@0.5.10
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: "frontend/.*\.(ts|tsx|js|jsx)"
        additional_dependencies:
          - eslint-config-next@14.2.4
          - typescript@5.4.5
