version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: isochronic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/isochronic
      SECRET_KEY: changeme
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["poetry", "run", "uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
  frontend:
    image: node:20.12-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    depends_on:
      - api
volumes:
  db_data:
