name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pip install poetry==1.8.3
      - name: Install deps
        run: poetry install --with dev --directory backend
      - name: Lint & Test
        run: |
          poetry run ruff check backend
          poetry run mypy backend
          poetry run pytest tests/backend
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: |
          cd frontend
          npm install
      - name: Lint
        run: |
          cd frontend
          npm run lint -- --no-cache
      - name: Test
        run: |
          cd frontend
          npm run test -- --run
      - name: Build
        run: |
          cd frontend
          npm run build
