# This workflow defines a Continuous Integration (CI) pipeline that is triggered
# on pushes to the 'main' branch and on any pull request.
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # The 'build' job runs on an Ubuntu runner.
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository's code.
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up the Java Development Kit (JDK).
      # This uses Java version 17 from the 'temurin' distribution.
      # It also caches Gradle dependencies to speed up future builds.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Step 3: Install Gradle so the build can run without a bundled wrapper.
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.14

      # Step 4: Build the project using the installed Gradle.
      # The 'build' task compiles the code, runs tests, and assembles the application.
      # The GRADLE_OPTS environment variable is used to disable the Gradle daemon,
      # which is recommended for CI environments.
      - name: Build with Gradle
        run: gradle build
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
